In [10]:
# 1. Run this first
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 100
pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv(r"E:\data sets\loan_data_set.csv")
print("Shape of the dataset (rows, columns):", df.shape)
print(f"Number of applicants (rows): {df.shape[0]}")
print(f"Number of variables (columns): {df.shape[1]}")

Shape of the dataset (rows, columns): (614, 13)
Number of applicants (rows): 614
Number of variables (columns): 13

In [3]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 62.5 KB

In [5]:
df.columns.tolist()

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [6]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [2]:
import pandas as pd
df = pd.read_csv(r"E:\data sets\loan_data_set.csv")

In [3]:
missing_flag = df.isnull().any()
print("Columns with missing values:")
print(missing_flag[missing_flag].index.tolist())

Columns with missing values:
['Gender', 'Married', 'Dependents', 'Self_Employed', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']

In [4]:
missing_count = df.isnull().sum()
non_missing_count = df.notnull().sum()
missing_pct = (missing_count / len(df) * 100).round(2)

missing_stats = pd.DataFrame({
    "Missing_Values": missing_count,
    "Non_Missing_Values": non_missing_count,
    "Missing_Percentage": missing_pct
}).sort_values("Missing_Values", ascending=False)

missing_stats

                   Missing_Values  Non_Missing_Values  Missing_Percentage
Credit_History                 50                 564                8.14
Self_Employed                  32                 582                5.21
LoanAmount                     22                 592                3.58
Dependents                     15                 599                2.44
Loan_Amount_Term               14                 600                2.28
Gender                         13                 601                2.12
Married                         3                 611                0.49
Education                       0                 614                0.00
Loan_ID                         0                 614                0.00
CoapplicantIncome               0                 614                0.00
ApplicantIncome                 0                 614                0.00
Property_Area                   0                 614                0.00
Loan_Status                     0                 614                0.00

In [5]:
total_missing = df.isnull().sum().sum()
total_non_missing = df.notnull().sum().sum()
total_cells = df.shape[0] * df.shape[1]
overall_missing_pct = round(total_missing / total_cells * 100, 2)

print(f"Total missing values in dataset : {total_missing}")
print(f"Total non-missing values        : {total_non_missing}")
print(f"Total cells (rows x columns)     : {total_cells}")
print(f"Overall percentage of empty cells: {overall_missing_pct}%")

Total missing values in dataset : 149
Total non-missing values        : 7833
Total cells (rows x columns)     : 7982
Overall percentage of empty cells: 1.87%

In [6]:
problematic = missing_stats[missing_stats["Missing_Values"] > 0].sort_values("Missing_Values", ascending=False)
problematic

                  Missing_Values  Non_Missing_Values  Missing_Percentage
Credit_History                50                 564                8.14
Self_Employed                 32                 582                5.21
LoanAmount                    22                 592                3.58
Dependents                    15                 599                2.44
Loan_Amount_Term              14                 600                2.28
Gender                        13                 601                2.12
Married                        3                 611                0.49

In [7]:
top_var = problematic.index[0]
print(f"Most problematic variable: '{top_var}' "
      f"with {problematic.loc[top_var, 'Missing_Values']} missing values "
      f"({problematic.loc[top_var, 'Missing_Percentage']}% of records).")

Most problematic variable: 'Credit_History' with 50 missing values (8.14% of records).

In [13]:
plt.figure(figsize=(10, 6))
ax = sns.barplot(
    x=problematic["Missing_Values"],
    y=problematic.index,
    hue=problematic.index,
    palette="Reds_r",
    legend=False
)
ax.set_title("Missing Values by Column — Loan Dataset", fontsize=14, fontweight="bold")
ax.set_xlabel("Number of Missing Values")
ax.set_ylabel("Column")

for i, v in enumerate(problematic["Missing_Values"]):
    ax.text(v + 0.5, i, str(v), va="center", fontsize=10)

plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [14]:
plt.figure(figsize=(10, 6))
sns.heatmap(df.isnull(), cbar=False, cmap="viridis", yticklabels=False)
plt.title("Missing Data Heatmap — Loan Dataset", fontsize=14, fontweight="bold")
plt.xlabel("Columns")
plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [13]:
student_data = {
    "Student": ["Ayesha", "Bilal", "Fatima", "Hassan", "Sara"],
    "Math": [88, 72, 95, 60, 79],
    "Science": [91, 68, 89, 74, 85],
    "English": [76, 81, 92, 65, 70]
}

students_df = pd.DataFrame(student_data)
students_df["Average"] = students_df[["Math", "Science", "English"]].mean(axis=1).round(2)
students_df

NameError: name 'pd' is not defined

In [6]:
plt.figure(figsize=(8, 5))
ax = sns.barplot(
    data=students_df,
    x="Student", y="Average",
    hue="Student",
    palette="viridis",
    legend=False
)
ax.set_title("Average Marks by Student", fontsize=14, fontweight="bold")
ax.set_ylabel("Average Marks (out of 100)")
ax.set_ylim(0, 100)

for i, v in enumerate(students_df["Average"]):
    ax.text(i, v + 1, str(v), ha="center", fontsize=10)

plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [3]:
students_long = students_df.melt(
    id_vars="Student",
    value_vars=["Math", "Science", "English"],
    var_name="Subject",
    value_name="Marks"
)

plt.figure(figsize=(9, 5))
sns.barplot(data=students_long, x="Student", y="Marks", hue="Subject", palette="Set2")
plt.title("Marks by Subject for Each Student", fontsize=14, fontweight="bold")
plt.ylim(0, 100)
plt.tight_layout()
plt.show()

NameError: name 'students_df' is not defined

In [2]:
plt.figure(figsize=(7, 5))
ax = sns.countplot(
    data=df,
    x="Property_Area",
    hue="Property_Area",
    order=df["Property_Area"].value_counts().index,
    palette="pastel",
    legend=False
)
ax.set_title("Applicant Count by Property Area", fontsize=14, fontweight="bold")
ax.set_xlabel("Property Area")
ax.set_ylabel("Number of Applicants")

for container in ax.containers:
    ax.bar_label(container)

plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [1]:
df["Property_Area"].value_counts()

NameError: name 'df' is not defined